kind: ConfigMap 
apiVersion: v1
metadata:
  name: demo-configmap 
data:
  # Configuration values can be set as key-value properties
  DATABASE_LOGGING: "true"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "nest"
  DB_USER: "root"
  DB_PASSWORD: "test"
  DATABASE_SYNC: "true"